[package]
name = "my-acton-project"
description = "A TON blockchain project"
version = "0.1.0"
license = "MIT"

[fmt]
width = 100
ignore = []

[import-mappings]
acton = ".acton"
contracts = "contracts"
gen = "gen"
tests = "tests"
wrappers = "wrappers"
